

logging:
  level:
    root: INFO
    com.jp: DEBUG


riot:
  api:
    # this key is just a transient dev key
    key: RGAPI-b824af1b-af22-4fd4-9d2b-aa9092ce5c89
    url:
      na: 'https://na1.api.riotgames.com'
      apiKey: '?api_key={apiKey}'
      league: '/lol/league/v3/positions/by-summoner/{summonerId}'
      summoner: '/lol/summoner/v3/summoners/by-name/{summonerName}'
      spectator: '/lol/spectator/v3/active-games/by-summoner/{summonerId}'
  tlsjpa:
    id: 20022284

