

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: loltracker

logging:
  level:
    root: INFO
    com.jp: DEBUG


riot:
  api:
    # this key is just a transient dev key
    key: RGAPI-48904141-392f-45c4-96f2-c5a3fe89a946
    url:
      na: 'https://na1.api.riotgames.com'
      apiKey: '?api_key={apiKey}'
      league: '/lol/league/v3/positions/by-summoner/{summonerId}'
      summoner: '/lol/summoner/v3/summoners/by-name/{summonerName}'
      spectator: '/lol/spectator/v3/active-games/by-summoner/{summonerId}'
  tlsjpa:
    id: 20022284

